export const MOSTVIEWED_RENDERING = "MOSTVIEWED_RENDERING"
export const NEWEST_RENDERING = "NEWEST_RENDERING"
export const LOWTOHIGH_RENDERING = "LOWTOHIGH_RENDERING"
export const HIGHTOLOW_RENDERING = "HIGHTOLOW_RENDERING"
