export const IMAGES = [
  {
    id: 0,
    title: "AI Napoleon",
    image: "/images/ai_napoleon.jpeg",
    price: 54321,
    views: 547,
  },
  {
    id: 1,
    title: "Blue Volcano",
    image: "/images/blue_volcano.jpg",
    price: 23840,
    views: 7335,
  },
  {
    id: 2,
    title: "Cats",
    image: "/images/cats.jpg",
    price: 67000,
    views: 8733,
  },
  {
    id: 3,
    title: "Edge of The Earth",
    image: "/images/edge-of-the-earth.jpg",
    price: 754,
    views: 56465,
  },
  {
    id: 4,
    title: "Elon and Doge",
    image: "/images/elon_and_doge.jpg",
    price: 987,
    views: 2908,
  },
  {
    id: 5,
    title: "Galaxy Raccoon",
    image: "/images/galaxyraccoon.jpg",
    price: 47500,
    views: 523,
  },
  {
    id: 6,
    title: "Geo Room",
    image: "/images/geo-room.jpg",
    price: 47500,
    views: 700,
  },
  {
    id: 7,
    title: "Goat SheMan",
    image: "/images/goat-sheman.webp",
    price: 435,
    views: 7437658,
  },
  {
    id: 8,
    title: "Laser Cloud",
    image: "/images/laser_cloud.jpg",
    price: 9764,
    views: 4327648,
  },
  {
    id: 9,
    title: "Nebula Shore",
    image: "/images/nebulashorejpg.jpg",
    price: 35422,
    views: 42958,
  },
  {
    id: 10,
    title: "Organic Mass",
    image: "/images/organic_mass.jpg",
    price: 6500,
    views: 479382,
  },
  {
    id: 11,
    title: "Pastel Street",
    image: "/images/pastel_street.jpg",
    price: 2525,
    views: 329685,
  },
  {
    id: 12,
    title: "Post Internet",
    image: "/images/post-internet.jpg",
    price: 8764,
    views: 689493,
  },
  {
    id: 13,
    title: "Priester Moon",
    image: "/images/priester-moon.jpg",
    price: 87675,
    views: 28596096,
  },
  {
    id: 14,
    title: "Pink Eclipse",
    image: "/images/priester-pink-eclipse.jpg",
    price: 8764,
    views: 3965891,
  },
  {
    id: 15,
    title: "Priester Tetra",
    image: "/images/priester-tetra.jpg",
    price: 1358,
    views: 6437642,
  },
  {
    id: 16,
    title: "Prism Cloud",
    image: "/images/prism-cloud.jpg",
    price: 4652,
    views: 277385,
  },
  {
    id: 17,
    title: "Rainbow Checkered Floor",
    image: "/images/rainbow-checkered-floor.jpeg",
    price: 94765,
    views: 27775,
  },
  {
    id: 18,
    title: "Uniswap",
    image: "/images/uniswap.jpg",
    price: 85245,
    views: 756437,
  },
  {
    id: 19,
    title: "Vaporwave in Space",
    image: "/images/vaporwave-in-space.jpg",
    price: 91894,
    views: 238709,
  },
  {
    id: 20,
    title: "Yo",
    image: "/images/yo.png",
    price: 2600,
    views: 654275,
  },
  {
    id: 21,
    title: "Irony",
    image: "/images/respect-the-earth.jpg",
    price: 35436,
    views: 8765484,
  },
]
